name: Second Action
on: [push]

jobs:
  First-job:
    if: false  # This condition will never be true, so the workflow won't run
    runs-on: ubuntu-latest
    steps:
      -  run: echo "Hello This is First-job."
      -  run: echo "First-job end."
  Second-job:
    if: false  # This condition will never be true, so the workflow won't run
    runs-on: ubuntu-latest
    steps:
      -  run:  echo "Hello This is Second-job."
      -  run:  echo "Second-job end."
