name: Sixth Workflow
run-name: RUN ONE OF 6TH WORKFLOW
#ENV VARIABLES AND 
on:
  push:
    branches:
      -  main

jobs:
  Set-env-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Set variable
        run: |
          echo "new_variable=Farhan Ahmed" >> "$GITHUB_ENV"
          echo "The operating system on the runner is $env:RUNNER_OS."
      - name: Get variable value
        run: |
          echo "My name is $new_variable"
          echo "City: $vars.CITY"
          echo "Your name: $vars.NAME"
      - name: End Job
        run: echo "Ending job"
