name: Sixth Workflow
run-name: RUN ONE OF 6TH WORKFLOW
#ENV VARIABLES AND 
on:
  push:
    branches:
      -  main

jobs:
  Set-env-variable:
    runs-on: windows-latest
    steps:
      - name: Set variable
        run: |
          echo "new_variable=Farhan Ahmed" >> "$GITHUB_ENV"
      - name: Get variable value
        run: echo $new_variable "|" $env:new_variable
      - name: End Job
        run: echo "Ending job"
